# Routes
get_user:
  path: /users/{uid}
  controller: App\Controller\GetUserController
  method: [GET]

put_user:
  path: /users/{uid}
  controller: App\Controller\PutUserController
  methods: [PUT]

