parameters:
    kernel.secret: yoursecretshouldbehere
    app_path: "../.."

framework:
    form: false
    assets: false
    session: false
    translator: false
    php_errors:
        log: false

command_bus:
    command_bus:
        middlewares:
            - Domain\Middleware\CheckUserNameLength

# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    #
    # Controllers
    #
    App\Controller\:
        resource : "%app_path%/src/Controller/*"
        tags:
            - {name: controller.service_arguments}
    
    Domain\QueryHandler\:
        resource: "%app_path%/src/Domain/QueryHandler/*"
        tags: 
            - {name: "query_handler"}

    Domain\CommandHandler\:
        resource: "%app_path%/src/Domain/CommandHandler/*"
        tags:
            - {name: "command_handler"}

    Domain\Middleware\:
        resource: "%app_path%/src/Domain/Middleware/*"

    Domain\Model\User\InMemoryUserRepository:
    Domain\Model\User\UserRepository:
        alias: Domain\Model\User\InMemoryUserRepository